/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace TicTacToeEscrow {
  export type GameStruct = {
    player1: AddressLike;
    player2: AddressLike;
    pot: BigNumberish;
    active: boolean;
    completed: boolean;
  };

  export type GameStructOutput = [
    player1: string,
    player2: string,
    pot: bigint,
    active: boolean,
    completed: boolean
  ] & {
    player1: string;
    player2: string;
    pot: bigint;
    active: boolean;
    completed: boolean;
  };
}

export interface TicTacToeEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CREATOR"
      | "CREATOR_FEE"
      | "ENTRY_FEE"
      | "PAYMASTER"
      | "USDC"
      | "WINNER_PAYOUT"
      | "createGame"
      | "createGameSponsored"
      | "gameCounter"
      | "games"
      | "getGame"
      | "getLeaderboard"
      | "getPlayerStats"
      | "joinGame"
      | "joinGameSponsored"
      | "losses"
      | "payout"
      | "totalGames"
      | "wins"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GameCompleted"
      | "GameCreated"
      | "GameJoined"
      | "SponsoredEntry"
  ): EventFragment;

  encodeFunctionData(functionFragment: "CREATOR", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "CREATOR_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ENTRY_FEE", values?: undefined): string;
  encodeFunctionData(functionFragment: "PAYMASTER", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "WINNER_PAYOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createGame",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createGameSponsored",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gameCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "games", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "joinGameSponsored",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "losses", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "payout",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalGames",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "wins", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "CREATOR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CREATOR_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ENTRY_FEE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PAYMASTER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "WINNER_PAYOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createGameSponsored",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gameCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "games", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "joinGameSponsored",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "losses", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payout", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalGames", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wins", data: BytesLike): Result;
}

export namespace GameCompletedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    winner: AddressLike,
    payout: BigNumberish
  ];
  export type OutputTuple = [gameId: bigint, winner: string, payout: bigint];
  export interface OutputObject {
    gameId: bigint;
    winner: string;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameCreatedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player1: AddressLike,
    player2: AddressLike
  ];
  export type OutputTuple = [gameId: bigint, player1: string, player2: string];
  export interface OutputObject {
    gameId: bigint;
    player1: string;
    player2: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameJoinedEvent {
  export type InputTuple = [gameId: BigNumberish, player2: AddressLike];
  export type OutputTuple = [gameId: bigint, player2: string];
  export interface OutputObject {
    gameId: bigint;
    player2: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SponsoredEntryEvent {
  export type InputTuple = [gameId: BigNumberish, player: AddressLike];
  export type OutputTuple = [gameId: bigint, player: string];
  export interface OutputObject {
    gameId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TicTacToeEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): TicTacToeEscrow;
  waitForDeployment(): Promise<this>;

  interface: TicTacToeEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CREATOR: TypedContractMethod<[], [string], "view">;

  CREATOR_FEE: TypedContractMethod<[], [bigint], "view">;

  ENTRY_FEE: TypedContractMethod<[], [bigint], "view">;

  PAYMASTER: TypedContractMethod<[], [string], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  WINNER_PAYOUT: TypedContractMethod<[], [bigint], "view">;

  createGame: TypedContractMethod<
    [opponent: AddressLike],
    [bigint],
    "nonpayable"
  >;

  createGameSponsored: TypedContractMethod<
    [player1: AddressLike, opponent: AddressLike],
    [bigint],
    "nonpayable"
  >;

  gameCounter: TypedContractMethod<[], [bigint], "view">;

  games: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, boolean] & {
        player1: string;
        player2: string;
        pot: bigint;
        active: boolean;
        completed: boolean;
      }
    ],
    "view"
  >;

  getGame: TypedContractMethod<
    [gameId: BigNumberish],
    [TicTacToeEscrow.GameStructOutput],
    "view"
  >;

  getLeaderboard: TypedContractMethod<
    [limit: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;

  getPlayerStats: TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, bigint] & {
        _wins: bigint;
        _losses: bigint;
        _total: bigint;
      }
    ],
    "view"
  >;

  joinGame: TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;

  joinGameSponsored: TypedContractMethod<
    [gameId: BigNumberish, player2: AddressLike],
    [void],
    "nonpayable"
  >;

  losses: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  payout: TypedContractMethod<
    [gameId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  totalGames: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  wins: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CREATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CREATOR_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ENTRY_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PAYMASTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WINNER_PAYOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createGame"
  ): TypedContractMethod<[opponent: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "createGameSponsored"
  ): TypedContractMethod<
    [player1: AddressLike, opponent: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gameCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "games"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, boolean] & {
        player1: string;
        player2: string;
        pot: bigint;
        active: boolean;
        completed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<
    [gameId: BigNumberish],
    [TicTacToeEscrow.GameStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLeaderboard"
  ): TypedContractMethod<[limit: BigNumberish], [[string[], bigint[]]], "view">;
  getFunction(
    nameOrSignature: "getPlayerStats"
  ): TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, bigint] & {
        _wins: bigint;
        _losses: bigint;
        _total: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinGame"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "joinGameSponsored"
  ): TypedContractMethod<
    [gameId: BigNumberish, player2: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "losses"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "payout"
  ): TypedContractMethod<
    [gameId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalGames"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "wins"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "GameCompleted"
  ): TypedContractEvent<
    GameCompletedEvent.InputTuple,
    GameCompletedEvent.OutputTuple,
    GameCompletedEvent.OutputObject
  >;
  getEvent(
    key: "GameCreated"
  ): TypedContractEvent<
    GameCreatedEvent.InputTuple,
    GameCreatedEvent.OutputTuple,
    GameCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GameJoined"
  ): TypedContractEvent<
    GameJoinedEvent.InputTuple,
    GameJoinedEvent.OutputTuple,
    GameJoinedEvent.OutputObject
  >;
  getEvent(
    key: "SponsoredEntry"
  ): TypedContractEvent<
    SponsoredEntryEvent.InputTuple,
    SponsoredEntryEvent.OutputTuple,
    SponsoredEntryEvent.OutputObject
  >;

  filters: {
    "GameCompleted(uint256,address,uint256)": TypedContractEvent<
      GameCompletedEvent.InputTuple,
      GameCompletedEvent.OutputTuple,
      GameCompletedEvent.OutputObject
    >;
    GameCompleted: TypedContractEvent<
      GameCompletedEvent.InputTuple,
      GameCompletedEvent.OutputTuple,
      GameCompletedEvent.OutputObject
    >;

    "GameCreated(uint256,address,address)": TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;
    GameCreated: TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;

    "GameJoined(uint256,address)": TypedContractEvent<
      GameJoinedEvent.InputTuple,
      GameJoinedEvent.OutputTuple,
      GameJoinedEvent.OutputObject
    >;
    GameJoined: TypedContractEvent<
      GameJoinedEvent.InputTuple,
      GameJoinedEvent.OutputTuple,
      GameJoinedEvent.OutputObject
    >;

    "SponsoredEntry(uint256,address)": TypedContractEvent<
      SponsoredEntryEvent.InputTuple,
      SponsoredEntryEvent.OutputTuple,
      SponsoredEntryEvent.OutputObject
    >;
    SponsoredEntry: TypedContractEvent<
      SponsoredEntryEvent.InputTuple,
      SponsoredEntryEvent.OutputTuple,
      SponsoredEntryEvent.OutputObject
    >;
  };
}
